CREATE TABLE `ALT_HATLAR` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`ANA_HAT_NO` INT(10) NOT NULL DEFAULT '0',
	`ALT_HAT_NO` INT(10) NOT NULL DEFAULT '0',
	`ALT_HAT_ADI` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`UZUNLUK` DOUBLE NULL DEFAULT '0',
	`DURAK_SAYISI` INT(11) NULL DEFAULT '0',
	`BASLANGIC` VARCHAR(50) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`DONUS` VARCHAR(50) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`HAT_KULLANIM` VARCHAR(50) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`BISIKLET_TRAMVAY` BIT(1) NULL DEFAULT 'b\'0\'',
	`UpdateTarihSaat` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `ANA_HAT_NO_ALT_HAT_NO` (`ANA_HAT_NO`, `ALT_HAT_NO`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM
AUTO_INCREMENT=1
;

CREATE TABLE `DURAKLAR` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`DURAK_NO` VARCHAR(6) NOT NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`DURAK_ADI` VARCHAR(50) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`TIPI` SMALLINT(6) NULL DEFAULT '0',
	`YON` SMALLINT(6) NULL DEFAULT '0',
	`ENLEM` VARCHAR(50) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`BOYLAM` VARCHAR(50) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`ADRES` VARCHAR(250) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`KAYIT_TARIHI` DATETIME NULL DEFAULT NULL,
	`DURAK_KULLANIM` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`BISIKLET_TRAMVAY` BIT(1) NULL DEFAULT 'b\'0\'',
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `DURAK_NO` (`DURAK_NO`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM
AUTO_INCREMENT=1
;
CREATE TABLE `HAT_DURAK_SIRA` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`ANA_HAT_NO` INT(10) NOT NULL DEFAULT '0',
	`ALT_HAT_NO` INT(10) NOT NULL DEFAULT '0',
	`DURAK_NO` VARCHAR(10) NOT NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`SIRA` INT(11) NOT NULL DEFAULT '0',
	`ISTIKAMET` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `ANA_HAT_NO_ALT_HAT_NO_SIRA` (`ANA_HAT_NO`, `ALT_HAT_NO`, `SIRA`, `DURAK_NO`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM
AUTO_INCREMENT=1
;
